/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import database.connection;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author nurul
 */
public class LaporanKedai extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public LaporanKedai() {
        initComponents();
    }
    
    private void grafikPendapatanTenant() {
        try {
            String query = "SELECT namatenant, SUM(pendapatanbersih) AS tenant FROM rekapitulasi_mingguan GROUP BY id_tenant";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(connection.getCon(), query);
            JFreeChart chart = ChartFactory.createBarChart3D("Grafik Pendapatan Tenant", "Nama Tenant", "Total Pendapatan Tenant", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Grafik Pendapatan Tenant", chart);
            frame.setVisible(true);
            frame.setSize(1200,700);
            frame.setLocationRelativeTo(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void grafikPendapatanKedai() {
        try {
            String query = "SELECT tanggalrekap, keuntungan FROM rekapitulasi_bulanan";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(connection.getCon(), query);
            JFreeChart chart = ChartFactory.createLineChart("Grafik Pendapatan Bulanan", "Tanggal Rekap", "Keuntungan Per Bulan", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Grafik Pendapatan Per Bulan", chart);
            frame.setVisible(true);
            frame.setSize(1200,700);
            frame.setLocationRelativeTo(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void grafikMenu() {
        try {
            String query = "SELECT namamenu, jumlahpesan FROM pemesanan";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(connection.getCon(), query);
            JFreeChart chart = ChartFactory.createLineChart("Grafik Pesanan Menu Pelanggan", "Jumlah Menu Dipesan", "Keuntungan Per Bulan", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Grafik Pendapatan Per Bulan", chart);
            frame.setVisible(true);
            frame.setSize(1200,700);
            frame.setLocationRelativeTo(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void previewReport(String filename, HashMap parameter, String jenis) {
        try {
            File fileReport = new File("src\\report\\" + filename);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(fileReport.getPath());
            parameter.put("tgl1", tgl1.getDate());
            parameter.put("tgl2", tgl2.getDate());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, connection.getCon());
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
            System.err.println("Error " + e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tgl1 = new com.toedter.calendar.JDateChooser();
        tgl2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbReportKedai = new javax.swing.JComboBox<>();
        btCetakReport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbGrafik = new javax.swing.JComboBox<>();
        btCetak = new javax.swing.JButton();
        lbClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Laporan & Grafik");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, -1));

        jTabbedPane1.setBackground(new java.awt.Color(26, 26, 46));
        jTabbedPane1.setForeground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(26, 26, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masukan Tanggal");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, 20));
        jPanel2.add(tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 67, 149, -1));
        jPanel2.add(tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 107, 149, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("s.d");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pilih Laporan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 90, -1));

        cbReportKedai.setBackground(new java.awt.Color(28, 31, 44));
        cbReportKedai.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbReportKedai.setForeground(new java.awt.Color(255, 255, 255));
        cbReportKedai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pemesanan", "Pengeluaran", "Rekapitulasi Harian", "Rekapitulasi Mingguan", "Rekapitulasi Bulanan" }));
        cbReportKedai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbReportKedaiItemStateChanged(evt);
            }
        });
        jPanel2.add(cbReportKedai, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 147, 149, 25));

        btCetakReport.setBackground(new java.awt.Color(28, 31, 44));
        btCetakReport.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btCetakReport.setForeground(new java.awt.Color(255, 255, 255));
        btCetakReport.setText("Cetak Laporan");
        btCetakReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakReportActionPerformed(evt);
            }
        });
        jPanel2.add(btCetakReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 193, 150, -1));

        jTabbedPane1.addTab("Laporan", jPanel2);

        jPanel3.setBackground(new java.awt.Color(26, 26, 46));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Grafik");

        cbGrafik.setBackground(new java.awt.Color(28, 31, 44));
        cbGrafik.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbGrafik.setForeground(new java.awt.Color(255, 255, 255));
        cbGrafik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pendapatan Kotor Tenant", "Pendapatan Per Bulan", "Pesanan Menu Pelanggan" }));
        cbGrafik.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGrafikItemStateChanged(evt);
            }
        });
        cbGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrafikActionPerformed(evt);
            }
        });

        btCetak.setBackground(new java.awt.Color(28, 31, 44));
        btCetak.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btCetak.setForeground(new java.awt.Color(255, 255, 255));
        btCetak.setText("Tampilkan Grafik");
        btCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbGrafik, 0, 176, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCetak)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grafik", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 290));

        lbClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCloseMousePressed(evt);
            }
        });
        jPanel1.add(lbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
         int ok = JOptionPane.showConfirmDialog(null, "Ingin Menampilkan Grafik?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if /*(!isError)*/ (ok == 0) {
                String GR = cbGrafik.getSelectedItem().toString();
                switch (GR) {
                    case "Pendapatan Kotor Tenant":
                        grafikPendapatanTenant();
                        break;
                    case "Pendapatan Per Bulan":
                        grafikPendapatanKedai();
                        break;
                    case "Pesanan Menu Pelanggan":
                        grafikMenu();
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Anda belum memilih laporan!");
                        break;
                }
        }
    }//GEN-LAST:event_btCetakActionPerformed

    private void cbGrafikItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGrafikItemStateChanged
        String GR = cbGrafik.getSelectedItem().toString();
        if (GR.equals("Pendapatan Kotor Tenant") || GR.equals("Pendapatan Per Bulan") || GR.equals("Pesanan Menu Pelanggan")) {
            // dateEnabled(false);
        } else {
            //dateEnabled(true);
            //ttgl_dari.requestFocus();
        }
    }//GEN-LAST:event_cbGrafikItemStateChanged

    private void btCetakReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakReportActionPerformed
         if (tgl1.getDate().equals("") || tgl2.getDate().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Tanggal Terlebih Dahulu!", "SDIT Bahrul Fikri", JOptionPane.INFORMATION_MESSAGE);
        } else {
            HashMap parameter = new HashMap();
            //boolean isError = false;
            int ok = JOptionPane.showConfirmDialog(null, "Ingin Mencetak Laporan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if /*(!isError)*/ (ok == 0) {
                String LP = cbReportKedai.getSelectedItem().toString();
                switch (LP) {
                    case "Pemesanan":
                        previewReport("pemesanan.jasper", parameter, LP);
                        break;
                    case "Pengeluaran":
                        previewReport("pengeluaran.jasper", parameter, LP);
                        break;
                    case "Rekapitulasi Harian":
                        previewReport("reportharian.jasper", parameter, LP);
                        break;
                    case "Rekapitulasi Mingguan":
                        previewReport("reportmingguan.jasper", parameter, LP);
                        break;
                    case "Rekapitulasi Bulanan":
                        previewReport("reportbulanan.jasper", parameter, LP);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Anda belum memilih laporan!");
                        break;
                }
            } else {
            }
        }
    }//GEN-LAST:event_btCetakReportActionPerformed

    private void cbReportKedaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbReportKedaiItemStateChanged
        String LP = cbGrafik.getSelectedItem().toString();
        if (LP.equals("Pemesanan") || LP.equals("Pengeluaran") || LP.equals("Rekapitulasi Harian") || LP.equals("Rekapitulasi Mingguan") || LP.equals("Rekapitulasi Bulanan")) {
            // dateEnabled(false);
        } else {
            //dateEnabled(true);
            //ttgl_dari.requestFocus();
        }
    }//GEN-LAST:event_cbReportKedaiItemStateChanged

    private void cbGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrafikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGrafikActionPerformed

    private void lbCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMousePressed
        dispose();
    }//GEN-LAST:event_lbCloseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanKedai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LaporanKedai().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCetak;
    private javax.swing.JButton btCetakReport;
    private javax.swing.JComboBox<String> cbGrafik;
    private javax.swing.JComboBox<String> cbReportKedai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbClose;
    private com.toedter.calendar.JDateChooser tgl1;
    private com.toedter.calendar.JDateChooser tgl2;
    // End of variables declaration//GEN-END:variables
}
